# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'staff.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import CallAPI
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QApplication, QMainWindow, QVBoxLayout, QHBoxLayout, QWidget, QPushButton, QLabel, QLineEdit, QTableView, QSplitter, QHeaderView, QMessageBox
from PyQt5 import QtGui, QtCore
from PyQt5.QtCore import Qt 
from PyQt5.QtGui import QImage, QPixmap
import createmember as new

class Ui_MainWindow(QtWidgets.QMainWindow):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1370, 900)
        MainWindow.setMaximumSize(QtCore.QSize(1280, 680))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.btn_log_lv1 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_log_lv1.setGeometry(QtCore.QRect(40, 140, 251, 101))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(22)
        self.btn_log_lv1.setFont(font)
        self.btn_log_lv1.setStyleSheet("QPushButton{\n"
"    background-color:rgb(0, 170, 127);\n"
"    color: white;\n"
"    border-style: outset;\n"
"    border-width: 2px;\n"
"    border-radius: 10px;\n"
"    border-color: white;\n"
"}\n"
"\n"
"QPushButton::pressed{\n"
"    background-color: rgb(224,224,0);\n"
"    border-style: inset;\n"
"}")
        self.btn_log_lv1.setObjectName("btn_log_lv1")
        self.btn_member_lv1 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_member_lv1.setGeometry(QtCore.QRect(340, 140, 221, 101))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(22)
        self.btn_member_lv1.setFont(font)
        self.btn_member_lv1.setStyleSheet("QPushButton{\n"
"    background-color:rgb(0, 40, 40);\n"
"    color: white;\n"
"    border-style: outset;\n"
"    border-width: 2px;\n"
"    border-radius: 10px;\n"
"    border-color: white;\n"
"}\n"
"\n"
"QPushButton::pressed{\n"
"    background-color: rgb(224,224,0);\n"
"    border-style: inset;\n"
"}")
        self.btn_member_lv1.setObjectName("btn_member_lv1")
        self.btn_ret_lv1 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_ret_lv1.setGeometry(QtCore.QRect(610, 140, 221, 101))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(22)
        self.btn_ret_lv1.setFont(font)
        self.btn_ret_lv1.setStyleSheet("QPushButton{\n"
"    background-color:rgb(120, 120, 127);\n"
"    color: white;\n"
"    border-style: outset;\n"
"    border-width: 2px;\n"
"    border-radius: 10px;\n"
"    border-color: white;\n"
"}\n"
"\n"
"QPushButton::pressed{\n"
"    background-color: rgb(224,224,0);\n"
"    border-style: inset;\n"
"}")
        self.btn_ret_lv1.setObjectName("btn_ret_lv1")
        self.btn_store_lv1 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_store_lv1.setGeometry(QtCore.QRect(890, 140, 221, 101))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(22)
        self.btn_store_lv1.setFont(font)
        self.btn_store_lv1.setStyleSheet("QPushButton{\n"
"    background-color:rgb(190,0,0);\n"
"    color: white;\n"
"    border-style: outset;\n"
"    border-width: 2px;\n"
"    border-radius: 10px;\n"
"    border-color: white;\n"
"}\n"
"\n"
"QPushButton::pressed{\n"
"    background-color: rgb(224,224,0);\n"
"    border-style: inset;\n"
"}")
        self.btn_store_lv1.setObjectName("btn_store_lv1")
        self.log_view = QtWidgets.QTableView(self.centralwidget)
        self.log_view.setGeometry(QtCore.QRect(0, 260, 1371, 641))
        self.log_view.setObjectName("log_view")
        self.member_view = QtWidgets.QTableView(self.centralwidget)
        self.member_view.setGeometry(QtCore.QRect(0, 260, 751, 621))
        self.member_view.setObjectName("member_vview")
        self.ret_view = QtWidgets.QTableView(self.centralwidget)
        self.ret_view.setGeometry(QtCore.QRect(0, 260, 921, 631))
        self.ret_view.setObjectName("ret_view")
        self.store_view = QtWidgets.QTableView(self.centralwidget)
        self.store_view.setGeometry(QtCore.QRect(-20, 340, 1381, 841))
        self.store_view.setObjectName("store_view")
        self.btn_remove = QtWidgets.QPushButton(self.centralwidget)
        self.btn_remove.setGeometry(QtCore.QRect(970, 270, 141, 61))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(22)
        self.btn_remove.setFont(font)
        self.btn_remove.setStyleSheet("QPushButton{\n"
"    background-color:rgb(255, 170, 127);\n"
"    color: white;\n"
"    border-style: outset;\n"
"    border-width: 2px;\n"
"    border-radius: 10px;\n"
"    border-color: white;\n"
"}\n"
"\n"
"QPushButton::pressed{\n"
"    background-color: rgb(224,224,0);\n"
"    border-style: inset;\n"
"}")
        self.btn_remove.setObjectName("btn_remove")
        self.btn_add_mem = QtWidgets.QPushButton(self.centralwidget)
        self.btn_add_mem.setGeometry(QtCore.QRect(800, 270, 141, 61))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(24)
        font.setBold(True)
        self.btn_add_mem.setFont(font)
        self.btn_add_mem.setStyleSheet("QPushButton{\n"
"    background-color:rgb(0, 220, 127);\n"
"    color: white;\n"
"    border-style: outset;\n"
"    border-width: 2px;\n"
"    border-radius: 10px;\n"
"    border-color: white;\n"
"}\n"
"\n"
"QPushButton::pressed{\n"
"    background-color: rgb(224,224,0);\n"
"    border-style: inset;\n"
"}")
        
        self.btn_add_mem.setObjectName("btn_add_mem")
        self.btn_ret_comf = QtWidgets.QPushButton(self.centralwidget)
        self.btn_ret_comf.setGeometry(QtCore.QRect(960, 270, 141, 61))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(22)
        self.btn_ret_comf.setFont(font)
        self.btn_ret_comf.setStyleSheet("QPushButton{\n"
"    background-color:rgb(0, 0, 127);\n"
"    color: white;\n"
"    border-style: outset;\n"
"    border-width: 2px;\n"
"    border-radius: 10px;\n"
"    border-color: white;\n"
"}\n"
"\n"
"QPushButton::pressed{\n"
"    background-color: rgb(224,224,0);\n"
"    border-style: inset;\n"
"}")
        self.btn_ret_comf.setObjectName("btn_ret_comf")

        self.btn_ret_canc = QtWidgets.QPushButton(self.centralwidget)
        self.btn_ret_canc.setGeometry(QtCore.QRect(1130, 270, 141, 61))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(22)
        self.btn_ret_canc.setFont(font)
        self.btn_ret_canc.setStyleSheet("QPushButton{\n"
"    background-color:rgb(0, 127, 0);\n"
"    color: white;\n"
"    border-style: outset;\n"
"    border-width: 2px;\n"
"    border-radius: 10px;\n"
"    border-color: white;\n"
"}\n"
"\n"
"QPushButton::pressed{\n"
"    background-color: rgb(224,224,0);\n"
"    border-style: inset;\n"
"}")
        self.btn_ret_canc.setObjectName("btn_ret_cancel")

        self.ret_text = QtWidgets.QLineEdit(self.centralwidget)
        self.ret_text.setObjectName("ret_text")
        self.ret_text.setGeometry(QtCore.QRect(960,350,401,61))
        self.ret_text.setFont(font)

        self.tbd_label = QtWidgets.QLabel(self.centralwidget)
        self.tbd_label.setGeometry(QtCore.QRect(40, 20, 101, 101))
        self.tbd_label.setAutoFillBackground(False)
        self.tbd_label.setText("")
        self.tbd_label.setPixmap(QtGui.QPixmap("image/tbd.png"))
        self.tbd_label.setScaledContents(True)
        self.tbd_label.setObjectName("tbd_logo")

        
        self.khoa_label = QtWidgets.QLabel(self.centralwidget)
        self.khoa_label.setGeometry(QtCore.QRect(340, 20, 101, 101))
        self.khoa_label.setAutoFillBackground(False)
        self.khoa_label.setText("")
        self.khoa_label.setPixmap(QtGui.QPixmap("image/cntt.png"))
        self.khoa_label.setScaledContents(True)
        self.khoa_label.setObjectName("khoa_logo")

        
        self.lib_label = QtWidgets.QLabel(self.centralwidget)
        self.lib_label.setGeometry(QtCore.QRect(160, 20, 131, 121))
        self.lib_label.setAutoFillBackground(False)
        self.lib_label.setText("")
        self.lib_label.setPixmap(QtGui.QPixmap("image/tbd_lib.png"))
        self.lib_label.setScaledContents(True)
        self.lib_label.setObjectName("lib_logo")

        self.name_member_label = QtWidgets.QLabel(self.centralwidget)
        self.name_member_label.setObjectName("New member name")
        self.name_member_label.setFont(font)
        self.name_member_label.setText("Họ tên")
        self.name_member_label.setGeometry(QtCore.QRect(1120,340,101,41))
        self.name_member_label.setWordWrap(True)

        self.id_member_label = QtWidgets.QLabel(self.centralwidget)
        self.id_member_label.setObjectName("New member id")
        self.id_member_label.setFont(font)
        self.id_member_label.setText("ID")
        self.id_member_label.setGeometry(QtCore.QRect(1120,390,101,41))

        self.email_member_label = QtWidgets.QLabel(self.centralwidget)
        self.email_member_label.setObjectName("New member email")
        self.email_member_label.setFont(font)
        self.email_member_label.setText("Email")
        self.email_member_label.setGeometry(QtCore.QRect(1120,440,101,41))

        self.phone_member_label = QtWidgets.QLabel(self.centralwidget)
        self.phone_member_label.setObjectName("New member phone")
        self.phone_member_label.setFont(font)
        self.phone_member_label.setText("SDT")
        self.phone_member_label.setGeometry(QtCore.QRect(1120,490,101,41))

        self.unit_member_label = QtWidgets.QLabel(self.centralwidget)
        self.unit_member_label.setObjectName("New member unit")
        self.unit_member_label.setFont(font)
        self.unit_member_label.setText("Đơn vị")
        self.unit_member_label.setGeometry(QtCore.QRect(1120,540,101,41))

        self.name_member = QtWidgets.QLineEdit(self.centralwidget)
        self.name_member.setObjectName("name_member")
        self.name_member.setGeometry(QtCore.QRect(810,340,301,41))
        self.name_member.setFont(font)

        self.id_member = QtWidgets.QLineEdit(self.centralwidget)
        self.id_member.setObjectName("id_member")
        self.id_member.setGeometry(QtCore.QRect(810,390,301,41))
        self.id_member.setFont(font)
        
        self.email_member = QtWidgets.QLineEdit(self.centralwidget)
        self.email_member.setObjectName("email_member")
        self.email_member.setGeometry(QtCore.QRect(810,440,301,41))
        self.email_member.setFont(font)

        self.phone_member = QtWidgets.QLineEdit(self.centralwidget)
        self.phone_member.setObjectName("phone_member")
        self.phone_member.setGeometry(QtCore.QRect(810,490,301,41))
        self.phone_member.setFont(font)

        self.unit_member = QtWidgets.QLineEdit(self.centralwidget)
        self.unit_member.setObjectName("unit_member")
        self.unit_member.setGeometry(QtCore.QRect(810,540,301,41))
        self.unit_member.setFont(font)

        self.btn_add_ok = QtWidgets.QPushButton(self.centralwidget)
        self.btn_add_ok.setGeometry(QtCore.QRect(810, 590, 150, 70))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(22)
        self.btn_add_ok.setFont(font)
        self.btn_add_ok.setStyleSheet("QPushButton{\n"
"    background-color:rgb(190,0,0);\n"
"    color: white;\n"
"    border-style: outset;\n"
"    border-width: 2px;\n"
"    border-radius: 10px;\n"
"    border-color: white;\n"
"}\n"
"\n"
"QPushButton::pressed{\n"
"    background-color: rgb(224,224,0);\n"
"    border-style: inset;\n"
"}")
        
        
        self.id_remove_member = QtWidgets.QLineEdit(self.centralwidget)
        self.id_remove_member.setObjectName("ID member")
        self.id_remove_member.setGeometry(QtCore.QRect(810,340,301,41))
        self.id_remove_member.setFont(font)
        
        self.id_remove_member_label = QtWidgets.QLabel(self.centralwidget)
        self.id_remove_member_label.setObjectName("ID member to remove")
        self.id_remove_member_label.setFont(font)
        self.id_remove_member_label.setText("ID")
        self.id_remove_member_label.setStyleSheet("QLabel { color : red; }")
        self.id_remove_member_label.setGeometry(QtCore.QRect(1120,340,101,41))
        self.id_remove_member_label.setWordWrap(True)

        self.btn_remove_ok = QtWidgets.QPushButton(self.centralwidget)
        self.btn_remove_ok.setGeometry(QtCore.QRect(810, 410, 150, 70))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(22)
        self.btn_remove_ok.setFont(font)
        self.btn_remove_ok.setStyleSheet("QPushButton{\n"
"    background-color:rgb(190,0,0);\n"
"    color: white;\n"
"    border-style: outset;\n"
"    border-width: 2px;\n"
"    border-radius: 10px;\n"
"    border-color: white;\n"
"}\n"
"\n"
"QPushButton::pressed{\n"
"    background-color: rgb(224,224,0);\n"
"    border-style: inset;\n"
"}")
        
       
       


        ## raise item
        self.btn_log_lv1.raise_()
        self.btn_member_lv1.raise_()
        self.btn_ret_lv1.raise_()
        self.btn_store_lv1.raise_()
        self.log_view.raise_()
        self.member_view.raise_()
        self.ret_view.raise_()
        self.store_view.raise_()
        self.btn_add_mem.raise_()
        self.btn_remove.raise_()
        self.btn_ret_comf.raise_()
        self.ret_text.raise_()
        self.phone_member.raise_()
        self.email_member.raise_()
        self.id_member.raise_()
        self.name_member.raise_()
        self.unit_member.raise_()
        self.id_member_label.raise_()
        self.email_member_label.raise_()
        self.name_member_label.raise_()
        self.unit_member_label.raise_()
        self.phone_member_label.raise_()
        self.btn_add_ok.raise_()
        self.id_remove_member_label.raise_()
        self.id_remove_member.raise_()
        self.btn_remove_ok.raise_()
        self.btn_ret_canc.raise_()
        self.lib_label.raise_()
        self.tbd_label.raise_()
        self.khoa_label.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        ## connect slot
        self.btn_log_lv1.clicked.connect(self.btn_log)
        self.btn_member_lv1.clicked.connect(self.btn_member)
        self.btn_ret_lv1.clicked.connect(self.btn_ret)
        self.btn_store_lv1.clicked.connect(self.btn_store)
        self.btn_remove.clicked.connect(self.btn_remove_mem)
        self.btn_ret_comf.clicked.connect(self.btn_comf)
        self.btn_add_mem.clicked.connect(self.btn_add_new_mem)
        self.btn_remove.clicked.connect(self.btn_rem_memb)
        self.btn_remove_ok.clicked.connect(self.remove_member)
        self.btn_add_ok.clicked.connect(self.add_member)
        self.btn_ret_canc.clicked.connect(self.btn_ret_cancel)

        ## hide item
        self.ret_item(False)
        self.member_item(False)
        self.store_item(False)
        self.log_item(True)
        self.add_member_item(False)
        self.remove_member_item(False)
        
        
    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "TBD Library"))
        self.btn_log_lv1.setText(_translate("MainWindow", "Lịch sử"))
        self.btn_member_lv1.setText(_translate("MainWindow", "Thành viên"))
        self.btn_ret_lv1.setText(_translate("MainWindow", "Trả sách"))
        self.btn_store_lv1.setText(_translate("MainWindow", "Kho sách"))
        self.btn_remove.setText(_translate("MainWindow", "Xóa"))
        self.btn_add_mem.setText(_translate("MainWindow", "Thêm"))
        self.btn_ret_comf.setText(_translate("MainWindow", "OK"))
        self.btn_add_ok.setText(_translate("MainWindow","OK"))
        self.btn_remove_ok.setText(_translate("MainWindow","OK"))
        self.btn_ret_canc.setText(_translate("MainWindow","Cancel"))

## item
  
    def show_message(self, body: str):
        msg = QMessageBox()
        msg.setText(body)
        msg.setWindowTitle("Thông báo")
        msg.exec_()    


    def log_item(self,param: bool):
        
        self.log_view.setVisible(param)

    
    def ret_item(self, param: bool):
        self.ret_text.setVisible(param)
        self.ret_view.setVisible(param)
        self.btn_ret_comf.setVisible(param)
        self.btn_ret_canc.setVisible(param)
        

    def add_member_item(self, param: bool):
        self.id_member_label.setVisible(param)
        self.name_member_label.setVisible(param)
        self.phone_member_label.setVisible(param)
        self.unit_member_label.setVisible(param)
        self.email_member_label.setVisible(param)
        self.id_member.setVisible(param)
        self.name_member.setVisible(param)
        self.phone_member.setVisible(param)
        self.unit_member.setVisible(param)
        self.email_member.setVisible(param)
        self.btn_add_ok.setVisible(param)


    def member_item(self, param: bool):
        self.member_view.setVisible(param)
        self.btn_add_mem.setVisible(param)
        self.btn_remove.setVisible(param)

    def store_item(self, param: bool):
        self.store_view.setVisible(param)

    def remove_member_item(self, param: bool):
        self.id_remove_member.setVisible(param)
        self.id_remove_member_label.setVisible(param)
        self.btn_remove_ok.setVisible(param)


        ## button event

    def add_member(self):
            fault = 0   
            id = str(self.id_member.text())
            name = str(self.name_member.text())
            unit = str(self.unit_member.text())
            phone = str(self.phone_member.text())
            if(len(phone)<10):
                self.show_message("SĐT không hợp lệ")
                fault +=1
                self.phone_member.setText("")
            email = str(self.email_member.text())
            if(not "@tbd.edu.vn" in email):
                self.show_message("Email không hợp lệ")
                self.email_member.setText("")
                fault +=1
            if(fault<=0):
                member =[]
                member.append(id)
                member.append(name)
                member.append(unit)
                member.append(phone)
                member.append(email)
                
                target = CallAPI.AddMember(member)
                if(target == 1):
                    new.createMember(id,email)
                    self.show_message("Đã thêm thành viên mới.")
                    self.id_member.setText("")
                    self.name_member.setText("")
                    self.unit_member.setText("")
                    self.phone_member.setText("")
                    self.email_member.setText("")
                    self.btn_member()
                else:
                    self.show_message("Thành viên đã tồn tại")
                    self.id_member.setText("")
                    self.name_member.setText("")
                    self.phone_member.setText("")
                    self.unit_member.setText("")
                    self.email_member.setText("")
            else:
                self.show_message("Các tham số không hợp lệ. \n Vui lòng thử lại")
        

    def remove_member(self):
            self.add_member_item(False)
            id = str(self.id_remove_member.text())
            if(len(id)==6):
                a = CallAPI.RemoveMember(id)
                if(a == 1):
                    self.show_message("Đã xóa thành công!")
                    self.id_remove_member.setText("")
                    self.btn_member()
                else:
                    self.show_message("ID không tồn tại")

            else:
                self.show_message("ID không tồn tại \n hoặc không hợp lệ.\n Vui lòng thử lại!")
                self.id_remove_member.setText("")


    def btn_add_new_mem(self):
        self.remove_member_item(False)
        self.add_member_item(True)


    def btn_rem_memb(self):
        self.add_member_item(False)
        self.remove_member_item(True)
        self.add_member_item(False)
  
    def btn_log(self):
        self.remove_member_item(False)
        self.add_member_item(False)
        self.store_item(False)
        self.member_item(False)
        self.ret_item(False)
        result = CallAPI.log()
        header = ["ID member","Tên thành viên","Đơn vị", "Tên sách", "ID sách", "Ngày mượn", "Ngày trả", "Tình trạng"]
        model = QtGui.QStandardItemModel(result.index.size, result.columns.size)
        for i,row in result.iterrows():
            for j,col in enumerate(result.columns):
                item = QtGui.QStandardItem(str(row[col]))
                item.setEditable(False)
                model.setItem(i,j,item)
                
                
        a = self.log_view
        
        model.setHeaderData(0,Qt.Orientation.Horizontal,header[0], QtCore.Qt.ItemDataRole.EditRole)
        model.setHeaderData(1,Qt.Orientation.Horizontal,header[1], QtCore.Qt.ItemDataRole.EditRole)
        model.setHeaderData(2,Qt.Orientation.Horizontal,header[2], QtCore.Qt.ItemDataRole.EditRole)
        model.setHeaderData(3,Qt.Orientation.Horizontal,header[3], QtCore.Qt.ItemDataRole.EditRole)
        model.setHeaderData(4,Qt.Orientation.Horizontal,header[4], QtCore.Qt.ItemDataRole.EditRole)
        model.setHeaderData(5,Qt.Orientation.Horizontal,header[5], QtCore.Qt.ItemDataRole.EditRole)
        model.setHeaderData(6,Qt.Orientation.Horizontal,header[6], QtCore.Qt.ItemDataRole.EditRole)
        model.setHeaderData(7,Qt.Orientation.Horizontal,header[7], QtCore.Qt.ItemDataRole.EditRole)
        a.setModel(model)
        a.setWordWrap(True)  
        a.setColumnWidth(0,70)
        a.setColumnWidth(1,350)
        a.setColumnWidth(2,90)
        a.setColumnWidth(3,400)
        a.setColumnWidth(4,70)
        a.setColumnWidth(5,100)
        a.setColumnWidth(6,100)
        a.setColumnWidth(7,200)
        
        a.show()
    
    def btn_member(self):
        self.store_item(False)
        self.add_member_item(False)
        self.log_item(False)
        self.member_item(True)
        self.ret_item(False)
        result = CallAPI.member()
        header = ["ID","Họ và tên","Đơn vị","SĐT","Email"]
        model = QtGui.QStandardItemModel(result.index.size, result.columns.size)
        for i,row in result.iterrows():
            for j,col in enumerate(result.columns):
                item = QtGui.QStandardItem(str(row[col]))
                item.setEditable(False)
                model.setItem(i,j,item)
                
                
        a = self.member_view
        
        model.setHeaderData(0,Qt.Orientation.Horizontal,header[0], QtCore.Qt.ItemDataRole.EditRole)
        model.setHeaderData(1,Qt.Orientation.Horizontal,header[1], QtCore.Qt.ItemDataRole.EditRole)
        model.setHeaderData(2,Qt.Orientation.Horizontal,header[2], QtCore.Qt.ItemDataRole.EditRole)
        model.setHeaderData(3,Qt.Orientation.Horizontal,header[3], QtCore.Qt.ItemDataRole.EditRole)
        model.setHeaderData(4,Qt.Orientation.Horizontal,header[4], QtCore.Qt.ItemDataRole.EditRole)
        a.setModel(model)
        a.setWordWrap(True)  
        a.setColumnWidth(0,50)
        a.setColumnWidth(1,181)
        a.setColumnWidth(2,70)
        a.setColumnWidth(3,200)
        a.setColumnWidth(4,250)
        a.show()

    
    def btn_ret(self):
        self.remove_member_item(False)
        self.add_member_item(False)
        self.log_item(False)
        self.ret_item(True)
        self.member_item(False)
        self.store_item(False)
        result = CallAPI.ret()
        header = ['ID', 'Họ và tên','Đơn vị','Tên sách','ID sách','Ngày mượn','Ngày trả', 'Tình trạng']
        model = QtGui.QStandardItemModel(result.index.size, result.columns.size)
        for i,row in result.iterrows():
            for j,col in enumerate(result.columns):
                item = QtGui.QStandardItem(str(row[col]))
                item.setEditable(False)
                model.setItem(i,j,item)
                
                
        a = self.ret_view
        
        model.setHeaderData(0,Qt.Orientation.Horizontal,header[0], QtCore.Qt.ItemDataRole.EditRole)
        model.setHeaderData(1,Qt.Orientation.Horizontal,header[1], QtCore.Qt.ItemDataRole.EditRole)
        model.setHeaderData(2,Qt.Orientation.Horizontal,header[2], QtCore.Qt.ItemDataRole.EditRole)
        model.setHeaderData(3,Qt.Orientation.Horizontal,header[3], QtCore.Qt.ItemDataRole.EditRole)
        model.setHeaderData(4,Qt.Orientation.Horizontal,header[4], QtCore.Qt.ItemDataRole.EditRole)
        model.setHeaderData(5,Qt.Orientation.Horizontal,header[5], QtCore.Qt.ItemDataRole.EditRole)
        model.setHeaderData(6,Qt.Orientation.Horizontal,header[6], QtCore.Qt.ItemDataRole.EditRole)
        model.setHeaderData(7,Qt.Orientation.Horizontal,header[7], QtCore.Qt.ItemDataRole.EditRole)
        a.setModel(model)
        a.setWordWrap(True)  
        a.setColumnWidth(0,50)
        a.setColumnWidth(1,141)
        a.setColumnWidth(2,70)
        a.setColumnWidth(3,321)
        a.setColumnWidth(4,50)
        a.setColumnWidth(5,95)
        a.setColumnWidth(6,95)
        a.setColumnWidth(7,95)
        a.show()

    def reload_ret(self):
        self.remove_member_item(False)
        self.add_member_item(False)
        self.log_item(False)
        self.ret_item(True)
        self.member_item(False)
        self.store_item(False)
        result = CallAPI.ret()
        header = ['ID', 'Họ và tên','Đơn vị','Tên sách','ID sách','Ngày mượn','Ngày trả', 'Tình trạng']
        model = QtGui.QStandardItemModel(result.index.size, result.columns.size)
        for i,row in result.iterrows():
            for j,col in enumerate(result.columns):
                item = QtGui.QStandardItem(str(row[col]))
                item.setEditable(False)
                model.setItem(i,j,item)
                
                
        a = self.ret_view
        
        model.setHeaderData(0,Qt.Orientation.Horizontal,header[0], QtCore.Qt.ItemDataRole.EditRole)
        model.setHeaderData(1,Qt.Orientation.Horizontal,header[1], QtCore.Qt.ItemDataRole.EditRole)
        model.setHeaderData(2,Qt.Orientation.Horizontal,header[2], QtCore.Qt.ItemDataRole.EditRole)
        model.setHeaderData(3,Qt.Orientation.Horizontal,header[3], QtCore.Qt.ItemDataRole.EditRole)
        model.setHeaderData(4,Qt.Orientation.Horizontal,header[4], QtCore.Qt.ItemDataRole.EditRole)
        model.setHeaderData(5,Qt.Orientation.Horizontal,header[5], QtCore.Qt.ItemDataRole.EditRole)
        model.setHeaderData(6,Qt.Orientation.Horizontal,header[6], QtCore.Qt.ItemDataRole.EditRole)
        model.setHeaderData(7,Qt.Orientation.Horizontal,header[7], QtCore.Qt.ItemDataRole.EditRole)
        a.setModel(model)
        a.setWordWrap(True)  
        a.setColumnWidth(0,50)
        a.setColumnWidth(1,141)
        a.setColumnWidth(2,70)
        a.setColumnWidth(3,321)
        a.setColumnWidth(4,50)
        a.setColumnWidth(5,95)
        a.setColumnWidth(6,95)
        a.setColumnWidth(7,95)
        a.show()

    def btn_store(self):
        self.remove_member_item(False)
        self.add_member_item(False)
        self.log_item(False)
        self.member_item(False)
        self.ret_item(False)
        self.store_item(True)
        result = CallAPI.store()
        header = ['ID','Chỉ số ISBN','DDC','Tác giả','Năm Xb','Tên sách','Nơi xb','Nhà xb','Trích dẫn']
        result = result.reindex(columns=header)
        model = QtGui.QStandardItemModel(result.index.size, len(header))
        for i,(index,row) in enumerate(result.iterrows()):
            for j,col in enumerate(result.columns):
                item = QtGui.QStandardItem(str(row[col]))
                item.setEditable(False)
                model.setItem(i,j,item)
                
                
        a = self.store_view
        
        model.setHeaderData(0,Qt.Orientation.Horizontal,header[0], QtCore.Qt.ItemDataRole.EditRole)
        model.setHeaderData(1,Qt.Orientation.Horizontal,header[1], QtCore.Qt.ItemDataRole.EditRole)
        model.setHeaderData(2,Qt.Orientation.Horizontal,header[2], QtCore.Qt.ItemDataRole.EditRole)
        model.setHeaderData(3,Qt.Orientation.Horizontal,header[3], QtCore.Qt.ItemDataRole.EditRole)
        model.setHeaderData(4,Qt.Orientation.Horizontal,header[4], QtCore.Qt.ItemDataRole.EditRole)
        model.setHeaderData(5,Qt.Orientation.Horizontal,header[5], QtCore.Qt.ItemDataRole.EditRole)
        model.setHeaderData(6,Qt.Orientation.Horizontal,header[6], QtCore.Qt.ItemDataRole.EditRole)
        model.setHeaderData(7,Qt.Orientation.Horizontal,header[7], QtCore.Qt.ItemDataRole.EditRole)
        model.setHeaderData(8,Qt.Orientation.Horizontal,header[8], QtCore.Qt.ItemDataRole.EditRole)
        a.setModel(model)
        a.setWordWrap(True)  
        a.setColumnWidth(0,50)
        a.setColumnWidth(1,130)
        a.setColumnWidth(2,70)
        a.setColumnWidth(3,200)
        a.setColumnWidth(4,70)
        a.setColumnWidth(5,400)
        a.setColumnWidth(6,95)
        a.setColumnWidth(7,95)
        a.setColumnWidth(8,400)
        a.show()
        
        

    def btn_remove_mem(self):
        self.add_member_item(False)
        
    
    def btn_comf(self):
        try:
            id =  str(self.ret_text.text())
            CallAPI.update_log(id, "Đã trả")
            self.ret_text.setText("")
            info = CallAPI.memfromlog(id)
            email = info[0]
            user = info[1]
            book = info[2]
            new.return_book_succes(email, user, book)
            self.show_message("Đã cập nhật trạng thái sách thành công")
            self.reload_ret()
        except:
            self.show_message("ID không hợp lệ")
            self.ret_text.setText("")

    def btn_ret_cancel(self):
        try: 
            id = str(self.ret_text.text())
            CallAPI.update_log(id, "Lỗi")
            self.ret_text.setText("")
            info = CallAPI.memfromlog(id)
            email = info[0]
            user = info[1]
            book = info[2]
            new.return_book_fail(email, user, book)
            self.show_message("Đã cập nhật trạng thái sách thành công")
            self.reload_ret()
        except:
            self.show_message("ID không hợp lệ")
            self.ret_text.setText("")
    



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
